#ifndef COLOR_H
#define COLOR_H
#pragma once

#include "Window.h"

typedef WORD Color;

enum COLOR : Color {
	BACK_BLACK = 0x0000,
	BACK_DARK_GRAY = BACKGROUND_INTENSITY,

	BACK_DARK_BLUE = BACKGROUND_BLUE,
	BACK_BLUE = BACKGROUND_BLUE | BACKGROUND_INTENSITY,
	BACK_LIGHT_BLUE = BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	BACK_TEAL = BACKGROUND_BLUE | BACKGROUND_GREEN,

	BACK_DARK_GREEN = BACKGROUND_GREEN,
	BACK_LIGHT_GREEN = BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	BACK_DARK_YELLOW = BACKGROUND_GREEN | BACKGROUND_RED,
	BACK_YELLOW = BACKGROUND_GREEN | BACKGROUND_RED | BACKGROUND_INTENSITY,

	BACK_DARK_RED = BACKGROUND_RED,
	BACK_RED = BACKGROUND_RED | BACKGROUND_INTENSITY,
	BACK_PURPLE = BACKGROUND_RED | BACKGROUND_BLUE,
	BACK_PINK = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY,

	BACK_LIGHT_GRAY = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_GREEN,
	BACK_WHITE = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY,



	TEXT_BLACK = 0x0000,
	TEXT_DARK_GRAY = FOREGROUND_INTENSITY,

	TEXT_DARK_BLUE = FOREGROUND_BLUE,
	TEXT_BLUE = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	TEXT_LIGHT_BLUE = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	TEXT_TEAL = FOREGROUND_BLUE | FOREGROUND_GREEN,

	TEXT_DARK_GREEN = FOREGROUND_GREEN,
	TEXT_LIGHT_GREEN = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	TEXT_DARK_YELLOW = FOREGROUND_GREEN | FOREGROUND_RED,
	TEXT_YELLOW = FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY,

	TEXT_DARK_RED = FOREGROUND_RED,
	TEXT_RED = FOREGROUND_RED | FOREGROUND_INTENSITY,
	TEXT_PURPLE = FOREGROUND_RED | FOREGROUND_BLUE,
	TEXT_PINK = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,

	TEXT_LIGHT_GRAY = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN,
	TEXT_WHITE = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY
};

#endif // COLOR_H